### ISSUE TITLE
Cannot install via pip

### ISSUE THREAD

**Issue by kirillsulim** [dogebuild/dogebuild#15]
```
(ve) su0@tower:~$ pip install dogebuild
Collecting dogebuild
  Downloading https://files.pythonhosted.org/packages/f6/56/53d628ce7b342d7e6d6cc6bdabd77d03b64ace778dad8f44393776e9a93e/dogebuild-0.2.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-w3swa_sd/dogebuild/setup.py", line 17, in <module>
        version=load_from('dogebuild.version').strip(),
      File "/tmp/pip-install-w3swa_sd/dogebuild/setup.py", line 11, in load_from
        with open(path.join(project_directory, file_name), encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-w3swa_sd/dogebuild/dogebuild.version'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-w3swa_sd/dogebuild/
```

**Comment by kirillsulim** [comment]
Just installed dogebuild on windows. Probably this is not actual now.
